server:
  port: 9000
  
eureka:
  instance:
    hostname: localhost
    
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: staff-service
        uri:
          lb://staff-service
        predicates:
        - Path=/grocery/api/staff/**
      - id: PRODUCT-SERVICE
        uri:
          lb://PRODUCT-SERVICE
        predicates:
        - Path=/grocery/api/product/**
      - id: LOGIN-SERVICE 
        uri:
          lb://LOGIN-SERVICE
        predicates:
        - Path=/grocery/api/login/**
      
            
    
  
